# Stage 1: Build the Angular app
FROM node:14.17-alpine as build

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the Angular app
RUN npm run build

# Stage 2: Create a lightweight container to serve the Angular app
FROM nginx:1.21-alpine

# Copy the built app from the previous stage
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html

# Expose port 80 for the NGINX server
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
